[profile.default]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 20000
via_ir = true
src = "src"
test = "test"
out = "out"
libs = ["lib"]
cache_path = "cache/foundry"

[fmt]
line_length = 100

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
